# Generated by Django 3.1.5 on 2021-01-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAYI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='retailorEndorsement',
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerAddress',
            field=models.CharField(max_length=50, verbose_name='Müşteri Adresi'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerMail',
            field=models.CharField(max_length=50, verbose_name='Müşteri Maili'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerName',
            field=models.CharField(max_length=100, verbose_name='Müşteri Adı, Soyadı'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customerPhone',
            field=models.CharField(max_length=50, verbose_name='Müşteri Telefonu'),
        ),
    ]
