# Generated by Django 3.1.4 on 2021-01-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0017_products_careperiod'),
        ('BAYI', '0002_auto_20210115_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(max_length=100, verbose_name='Sipariş Adı')),
                ('customerName', models.CharField(max_length=100, verbose_name='Müşteri Adı, Soyadı')),
                ('orderAmount', models.IntegerField(default=0, verbose_name='Sipariş Miktarı')),
                ('orderDate', models.DateField(verbose_name='Sipariş Tarihi')),
                ('estimatedDelivery', models.DateField(verbose_name='Tahmini Teslim Süresi')),
                ('orderStatus', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSB.products', verbose_name='Ürün')),
            ],
        ),
    ]
