# Generated by Django 3.1.4 on 2021-01-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAYI', '0004_customersorders_pricesold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersorders',
            name='customerName',
        ),
        migrations.AddField(
            model_name='customersorders',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='BAYI.customers', verbose_name='Müşteri'),
            preserve_default=False,
        ),
    ]
