# Generated by Django 3.1.5 on 2021-01-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0018_auto_20210116_2105'),
        ('BAYI', '0008_payment_paymentmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='retailor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SSB.retailors', verbose_name='Bayi Adı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSB.orders', verbose_name='Bayi Siparişleri'),
        ),
    ]
