# Generated by Django 3.1.5 on 2021-01-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAYI', '0009_auto_20210117_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentBayiName',
            field=models.CharField(default=0, max_length=100, verbose_name='Bayi Ödeme Adı'),
            preserve_default=False,
        ),
    ]
