# Generated by Django 3.1.5 on 2021-01-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0018_auto_20210116_2105'),
        ('BAYI', '0010_payment_paymentbayiname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentNot',
            field=models.TextField(max_length=100, verbose_name='Ödeme Notu'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDescription', models.TextField(max_length=100, verbose_name='Bakım Açıklaması')),
                ('maintenanceCost', models.FloatField(default=0, verbose_name='Bakım Maliyeti')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAYI.customers', verbose_name='Müşteri')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSB.products', verbose_name='Ürün')),
            ],
        ),
    ]
