# Generated by Django 3.1.5 on 2021-01-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAYI', '0011_auto_20210117_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='customerMaintenanceName',
            field=models.CharField(default=0, max_length=100, verbose_name='Müşteri Adı'),
            preserve_default=False,
        ),
    ]
