# Generated by Django 3.1.4 on 2021-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='productSerial',
            field=models.IntegerField(default=0),
        ),
    ]
