# Generated by Django 3.1.4 on 2021-01-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0003_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materialStockCount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materials',
            name='tresholdValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materials',
            name='unitPrice',
            field=models.FloatField(default=0),
        ),
    ]
