# Generated by Django 3.1.4 on 2021-01-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0004_auto_20210101_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=100)),
                ('recipeCreationDate', models.DateField()),
                ('recipeTotalPrice', models.FloatField(default=0)),
                ('recipeSingleProductPrice', models.FloatField(default=0)),
            ],
        ),
    ]
