# Generated by Django 3.1.4 on 2021-01-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0005_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='productName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SSB.products'),
            preserve_default=False,
        ),
    ]
