# Generated by Django 3.1.4 on 2021-01-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0006_recipes_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='productName',
            new_name='product',
        ),
    ]
