# Generated by Django 3.1.4 on 2021-01-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0007_auto_20210101_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipeTotalPrice',
            new_name='recipeAdditionalCosts',
        ),
    ]
