# Generated by Django 3.1.4 on 2021-01-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0008_auto_20210101_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipeProductionCount',
            field=models.IntegerField(default=0),
        ),
    ]
