# Generated by Django 3.1.4 on 2021-01-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0009_recipes_recipeproductioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='estimatedDelivery',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(max_length=100)),
                ('dealerName', models.CharField(max_length=50)),
                ('orderAmount', models.IntegerField(default=0)),
                ('orderDate', models.DateField()),
                ('estimatedDelivery', models.DateField()),
                ('orderedProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSB.products')),
            ],
        ),
    ]
