# Generated by Django 3.1.4 on 2021-01-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0010_auto_20210102_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailorName', models.CharField(max_length=100)),
                ('retailorPhone', models.CharField(max_length=50)),
                ('retailorAddress', models.TextField()),
                ('retailorEndorsement', models.FloatField(default=0)),
            ],
        ),
    ]
