# Generated by Django 3.1.4 on 2021-01-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0011_retailors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dealerName',
        ),
        migrations.AddField(
            model_name='orders',
            name='retailor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SSB.retailors', verbose_name='Bayi Adı'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='estimatedDelivery',
            field=models.DateField(verbose_name='Tahmini Teslim Süresi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderAmount',
            field=models.IntegerField(default=0, verbose_name='Sipariş Miktarı'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(verbose_name='Sipariş Tarihi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderName',
            field=models.CharField(max_length=100, verbose_name='Sipariş Adı'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderedProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSB.products', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='products',
            name='estimatedDelivery',
            field=models.IntegerField(default=0, verbose_name='Tahmini Teslim Süresi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productDescription',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(upload_to='pics', verbose_name='Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=100, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productPrice',
            field=models.IntegerField(default=0, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productSerial',
            field=models.IntegerField(default=0, verbose_name='Sipariş Numarası'),
        ),
        migrations.AlterField(
            model_name='retailors',
            name='retailorAddress',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='retailors',
            name='retailorEndorsement',
            field=models.FloatField(default=0, verbose_name='Ciro (TL)'),
        ),
        migrations.AlterField(
            model_name='retailors',
            name='retailorName',
            field=models.CharField(default='', max_length=100, verbose_name='Bayi Adı'),
        ),
        migrations.AlterField(
            model_name='retailors',
            name='retailorPhone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
    ]
