# Generated by Django 3.1.4 on 2021-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0013_auto_20210109_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderStatus',
            field=models.BooleanField(default=False),
        ),
    ]
