# Generated by Django 3.1.4 on 2021-01-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0014_orders_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SSB.materials', verbose_name='Hammaddeler'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderStatus',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSB.products', verbose_name='Ürün'),
        ),
    ]
