# Generated by Django 3.1.4 on 2021-01-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0015_auto_20210113_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='materials',
        ),
        migrations.AddField(
            model_name='recipes',
            name='materials',
            field=models.ManyToManyField(to='SSB.Materials', verbose_name='Hammaddeler'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipeAdditionalCosts',
            field=models.FloatField(default=0, verbose_name='Ek Giderler'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipeName',
            field=models.CharField(max_length=100, verbose_name='Reçete Adı'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipeProductionCount',
            field=models.IntegerField(default=0, verbose_name='Üretim Adedi'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipeSingleProductPrice',
            field=models.FloatField(default=0, verbose_name='Tek Ürün Maliyeti'),
        ),
    ]
