# Generated by Django 3.1.4 on 2021-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSB', '0016_auto_20210113_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='carePeriod',
            field=models.IntegerField(default=0, verbose_name='Bakım Periyodu'),
        ),
    ]
